# Generated by Django 4.2.3 on 2023-08-08 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0008_faq_yttasker_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yttasker_payout',
            name='tasker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
