# Generated by Django 4.2.3 on 2023-08-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_yttasker_payout_tasker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AlterField(
            model_name='task',
            name='point',
            field=models.FloatField(default=0.02),
        ),
        migrations.DeleteModel(
            name='YTTasker_payout',
        ),
    ]
